name: Test Package Installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 libgl1 libxcb-xinerama0 libxcb-icccm4 libxcb-image0 \
            libxcb-keysyms1 libxcb-render-util0 libxcb-xfixes0 libx11-xcb1 libxcb1 libxcb-render0 libxrender1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and build dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install package
        run: pip install -e .

      - name: Run main()
        run: python -c "from SideScanSonarEditor.app import main; main()"
