name: Test

on:
  push:
  pull_request:
    branches: [ master, actions-tests ]

jobs:
  test:
    name: ${{ matrix.os }} / py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]
        python_version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest

